trigger:
- main

pool:
  name: 'Default'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'

- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    cd src
    npm install
    npm run build
  displayName: 'Install Node.js dependencies and build React app'

- script: |
    pip install -r requirements.txt
    python manage.py test
  displayName: 'Install Python dependencies and run tests'
